version: "2.1"

services:
    db:
        restart: always
        image: mysql
        command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ExpenseSubmitSystem
        ports:
            - "3308:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    web:
        restart: always
        build: ./web
        image: youchendu/expensesubmitsystem_web
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:db
        expose:
            - "8005"
    nginx:
        restart: always
        build: ./nginx
        image: youchendu/expensesubmitsystem_nginx
        ports:
            - "9020:8005"
        links:
            - web:web
        volumes_from:
            - web
