# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, default='', max_length=200, verbose_name='详细说明')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('type', models.CharField(choices=[('office', '日常办公用品费'), ('books', '书报杂志订阅费'), ('prints', '印刷费'), ('poundage', '手续费'), ('postage', '邮电费'), ('telephone', '电话费'), ('internet', '网络通讯费'), ('traffic', '交通费'), ('maintainance', '维护费'), ('conference', '会议费'), ('material', '专用材料费'), ('coorperation', '科研协作费'), ('subcontract', '委托业务费'), ('school_management', '学校管理费'), ('base_management', '基层管理费'), ('water_electric', '水电费'), ('rent', '租赁费'), ('equipment', '专用设备购置费'), ('software', '软件购置费'), ('hotel', '住宿费'), ('other', '其他费用')], max_length=30, verbose_name='类别')),
            ],
            options={
                'verbose_name': '发票信息',
                'verbose_name_plural': '发票信息',
            },
        ),
        migrations.CreateModel(
            name='BillSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('count', models.IntegerField(verbose_name='总单据数')),
                ('amount', models.FloatField(verbose_name='总金额')),
                ('status', models.CharField(choices=[('submit', '提交'), ('reject', '拒绝'), ('approve', '修改'), ('approve', '批准')], max_length=30, verbose_name='报销单状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User', verbose_name='申报人')),
            ],
            options={
                'verbose_name': '报销单',
                'verbose_name_plural': '报销单',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='billinfo',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.BillSheet'),
        ),
    ]
