# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('level_e', '普通用户'), ('level_a', '平台管理员'), ('level_s', '系统管理员')], default='level_e', max_length=20, verbose_name='权限等级'),
        ),
    ]
